#!/bin/sh
# shellcheck disable=1091

exec 2>&1

# wait for the pipewire media session daemon to start
sv check ~/.runit/sv/pipewire-media-session >/dev/null || exit 1

[ -r ./conf ] && . ./conf

if "$LOGGING_ENABLE" && [ "$LOG_LEVEL" != "" ]; then
  export PIPEWIRE_DEBUG="$LOG_LEVEL"
fi

# shfmt:ignore
# shellcheck disable=2086
exec pipewire-pulse $OPTS
