#!/bin/sh
# shellcheck disable=1091

[ -r ../conf ] && . ../conf

if "$LOGGING_ENABLE"; then
  [ -d "$LOG_DIR" ] || mkdir -p "$LOG_DIR"

  exec svlogd -tt "$LOG_DIR"
else
  exec chpst -b bspwm-log-null cat >/dev/null
fi
