#!/bin/sh
# shellcheck disable=1091

exec 2>&1

[ -r ./conf ] && . ./conf

if "$LOGGING_ENABLE" && [ "$LOG_LEVEL" != "" ]; then
  export PIPEWIRE_DEBUG="$LOG_LEVEL"
fi

# shfmt:ignore
# shellcheck disable=2086
exec pipewire $OPTS
