#!/bin/sh
# shellcheck disable=1091

# wait for the pipewire daemon to start
sv check ~/.runit/sv/pipewire >/dev/null || exit 1

[ -r ./conf ] && . ./conf

if "$LOGGING_ENABLE" && [ "$LOG_LEVEL" != "" ]; then
  export WIREPLUMBER_DEBUG="$LOG_LEVEL"
fi

# shellcheck disable=2086
# shfmt:ignore
exec wireplumber $OPTS 2>&1
