#!/bin/bash
# base16-shell (https://github.com/chriskempson/base16-shell)
# Base16 Shell template by Chris Kempson (http://chriskempson.com)
# Horizon Dark scheme by Michaël Ball (http://github.com/michael-ball/)
color00="1a/1c/27" # Base01 Black
color01="E9/56/78" # Base08 Red
color02="29/D3/98" # Base0B Green
color03="FA/C2/9A" # Base0A Yellow
color04="26/BB/D9" # Base0D Blue
color05="EE/64/FC" # Base0E Magenta
color06="59/E1/E3" # Base0C Cyan
color07="CB/CE/D9" # Base05 White
color08="67/6A/8D" # Base03 Bright Black
color09="EE/3B/3B" # Base08 Bright Red
color10="51/FF/9A" # Base0B Bright Green
color11="FF/D4/5D" # Base0A Bright Yellow
color12="1E/90/FF" # Base0D Bright Blue
color13="FE/A4/FF" # Base0E Bright Magenta
color14="59/E1/E3" # Base0C Bright Cyan
color15="E3/E6/EE" # Base07 Bright White
color16="1A/1C/27" # Base09
color17="1A/1C/27" # Base0F
color18="14/16/1E" # Base01
color19="2A/2C/40" # Base02
color20="CE/D1/E6" # Base04
color21="DC/DF/F4" # Base06

color_foreground="$color07"
# ~/scripts/color-brightness "${color00,,/,}" 0.2 | sed 's/^#//;s/../\//g'
color_background="05/06/08"

case "$TERM" in
  linux | tmux)
    color00="00/00/00"
    color08="00/00/00"
    color_background="00/00/00"
    ;;
esac

# shfmt:ignore-begin
if [ "${TERM%-*}" = 'fbterm' ] || [ -n "$FBTERM" ]; then
  # ESC [ 3 ; n ; r ; g ; b }
  put_template() {
    mapfile -t rgb < <(printf '%d\n' 0x${2//\// 0x})
    printf '\e[3;%d;%d;%d;%d}' "$1" "${rgb[0]}" "${rgb[1]}" "${rgb[2]}"
  }
  put_template_var() { :; }
  put_template_custom() { :; }
elif [ -n "$TMUX" ]; then
  # Tell tmux to pass the escape sequences through
  # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
  put_template() { printf '\033Ptmux;\033\033]4;%d;rgb:%s\033\033\\\033\\' $@; }
  put_template_var() { printf '\033Ptmux;\033\033]%d;rgb:%s\033\033\\\033\\' $@; }
  put_template_custom() { printf '\033Ptmux;\033\033]%s%s\033\033\\\033\\' $@; }
elif [ "${TERM%%[-.]*}" = "screen" ]; then
  # GNU screen (screen, screen-256color, screen-256color-bce)
  put_template() { printf '\033P\033]4;%d;rgb:%s\007\033\\' $@; }
  put_template_var() { printf '\033P\033]%d;rgb:%s\007\033\\' $@; }
  put_template_custom() { printf '\033P\033]%s%s\007\033\\' $@; }
elif [ "${TERM%%-*}" = "linux" ]; then
  put_template() { [ "$1" -lt 16 ] && printf "\e]P%x%s" ${@///}; }
  put_template_var() { :; }
  put_template_custom() { :; }
else
  put_template() { printf '\033]4;%d;rgb:%s\033\\' $@; }
  put_template_var() { printf '\033]%d;rgb:%s\033\\' $@; }
  put_template_custom() { printf '\033]%s%s\033\\' $@; }
fi
# shfmt:ignore-end

# 16 color space
put_template 0 "$color00"
put_template 1 "$color01"
put_template 2 "$color02"
put_template 3 "$color03"
put_template 4 "$color04"
put_template 5 "$color05"
put_template 6 "$color06"
put_template 7 "$color07"
put_template 8 "$color08"
put_template 9 "$color09"
put_template 10 "$color10"
put_template 11 "$color11"
put_template 12 "$color12"
put_template 13 "$color13"
put_template 14 "$color14"
put_template 15 "$color15"

# 256 color space
put_template 16 "$color16"
put_template 17 "$color17"
put_template 18 "$color18"
put_template 19 "$color19"
put_template 20 "$color20"
put_template 21 "$color21"

# foreground / background / cursor color
put_template_var 10 "$color_foreground"
if [ "$BASE16_SHELL_SET_BACKGROUND" != false ]; then
  put_template_var 11 "$color_background"
  if [ "${TERM%%-*}" = "rxvt" ]; then
    put_template_var 708 "$color_background" # internal border (rxvt)
  fi
fi
put_template_custom 12 ";7" # cursor (reverse video)

# clean up
unset -f put_template
unset -f put_template_var
unset -f put_template_custom
unset color00
unset color01
unset color02
unset color03
unset color04
unset color05
unset color06
unset color07
unset color08
unset color09
unset color10
unset color11
unset color12
unset color13
unset color14
unset color15
unset color16
unset color17
unset color18
unset color19
unset color20
unset color21
unset color_foreground
unset color_background
