#!/bin/bash

exec /usr/bin/qemu-system-x86_64 \
  -display sdl,grab-mod=lshift-lctrl-lalt \
  -name guest=win7-2,debug-threads=on \
  -machine pc-q35-7.0,usb=off,dump-guest-core=off \
  -accel kvm \
  -cpu host,migratable=on \
  -m 1024 \
  -overcommit mem-lock=off \
  -smp 1,sockets=1,dies=1,cores=1,threads=1 \
  -uuid 8ec3fd92-4930-4b1c-a46a-85b20400c655 \
  -no-user-config \
  -nodefaults \
  -no-hpet \
  -no-shutdown \
  -boot menu=off,strict=on \
  -device '{"driver":"pcie-root-port","port":16,"chassis":1,"id":"pci.1","bus":"pcie.0","multifunction":true,"addr":"0x2"}' \
  -device '{"driver":"pcie-root-port","port":17,"chassis":2,"id":"pci.2","bus":"pcie.0","addr":"0x2.0x1"}' \
  -device '{"driver":"pcie-root-port","port":18,"chassis":3,"id":"pci.3","bus":"pcie.0","addr":"0x2.0x2"}' \
  -device '{"driver":"pcie-root-port","port":19,"chassis":4,"id":"pci.4","bus":"pcie.0","addr":"0x2.0x3"}' \
  -device '{"driver":"pcie-pci-bridge","id":"pci.5","bus":"pci.1","addr":"0x0"}' \
  -device '{"driver":"ich9-usb-ehci1","id":"usb","bus":"pcie.0","addr":"0x1d.0x7"}' \
  -device '{"driver":"ich9-usb-uhci1","masterbus":"usb.0","firstport":0,"bus":"pcie.0","multifunction":true,"addr":"0x1d"}' \
  -device '{"driver":"ich9-usb-uhci2","masterbus":"usb.0","firstport":2,"bus":"pcie.0","addr":"0x1d.0x1"}' \
  -device '{"driver":"ich9-usb-uhci3","masterbus":"usb.0","firstport":4,"bus":"pcie.0","addr":"0x1d.0x2"}' \
  -device '{"driver":"virtio-serial-pci","id":"virtio-serial0","bus":"pci.2","addr":"0x0"}' \
  -device '{"driver":"usb-ccid","id":"ccid0","bus":"usb.0","port":"1"}' \
  -netdev user,id=hostnet0 \
  -device '{"driver":"rtl8139","netdev":"hostnet0","id":"net0","mac":"52:54:00:23:f7:a6","bus":"pci.5","addr":"0x1"}' \
  -device '{"driver":"usb-tablet","id":"input0","bus":"usb.0","port":"2"}' \
  -blockdev '{"driver":"file","filename":"/home/jaagr/.local/share/gnome-boxes/images/win7-2","node-name":"libvirt-2-storage","cache":{"direct":false,"no-flush":false},"auto-read-only":true,"discard":"unmap"}' \
  -blockdev '{"node-name":"libvirt-2-format","read-only":false,"cache":{"direct":false,"no-flush":false},"driver":"qcow2","file":"libvirt-2-storage","backing":null}' \
  -device '{"driver":"ide-hd","bus":"ide.0","drive":"libvirt-2-format","id":"sata0-0-0","bootindex":1,"write-cache":"on"}' \
  -device '{"driver":"ide-cd","bus":"ide.2","id":"sata0-0-2"}' \
  -device '{"driver":"qxl-vga","id":"video0","max_outputs":1,"ram_size":67108864,"vram_size":67108864,"vram64_size_mb":0,"vgamem_mb":16,"bus":"pcie.0","addr":"0x1"}' \
  -chardev spicevmc,id=charredir0,name=usbredir \
  -device '{"driver":"usb-redir","chardev":"charredir0","id":"redir0","bus":"usb.0","port":"3"}' \
  -device '{"driver":"virtio-balloon-pci","id":"balloon0","bus":"pci.3","addr":"0x0"}' \
  -chardev spicevmc,id=charredir1,name=usbredir \
  -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny \
  -msg timestamp=on

# -smp 1,sockets=1,dies=1,cores=1,threads=1 \
# -uuid 8ec3fd92-4930-4b1c-a46a-85b20400c655 \
# -no-user-config \
# -nodefaults \
# -rtc base=localtime,driftfix=slew \
# -global kvm-pit.lost_tick_policy=delay \
# -no-hpet \
# -no-shutdown \
# -global ICH9-LPC.disable_s3=1 \
# -global ICH9-LPC.disable_s4=1 \
# -boot menu=off,strict=on \
# -device '{"driver":"pcie-root-port","port":16,"chassis":1,"id":"pci.1","bus":"pcie.0","multifunction":true,"addr":"0x2"}' \
# -device '{"driver":"pcie-root-port","port":17,"chassis":2,"id":"pci.2","bus":"pcie.0","addr":"0x2.0x1"}' \
# -device '{"driver":"pcie-root-port","port":18,"chassis":3,"id":"pci.3","bus":"pcie.0","addr":"0x2.0x2"}' \
# -device '{"driver":"pcie-root-port","port":19,"chassis":4,"id":"pci.4","bus":"pcie.0","addr":"0x2.0x3"}' \
# -device '{"driver":"pcie-pci-bridge","id":"pci.5","bus":"pci.1","addr":"0x0"}' \
# -device '{"driver":"ich9-usb-ehci1","id":"usb","bus":"pcie.0","addr":"0x1d.0x7"}' \
# -device '{"driver":"ich9-usb-uhci1","masterbus":"usb.0","firstport":0,"bus":"pcie.0","multifunction":true,"addr":"0x1d"}' \
# -device '{"driver":"ich9-usb-uhci2","masterbus":"usb.0","firstport":2,"bus":"pcie.0","addr":"0x1d.0x1"}' \
# -device '{"driver":"ich9-usb-uhci3","masterbus":"usb.0","firstport":4,"bus":"pcie.0","addr":"0x1d.0x2"}' \
# -device '{"driver":"virtio-serial-pci","id":"virtio-serial0","bus":"pci.2","addr":"0x0"}' \
# -device '{"driver":"usb-ccid","id":"ccid0","bus":"usb.0","port":"1"}' \
# -blockdev '{"driver":"file","filename":"/home/jaagr/.local/share/gnome-boxes/images/win7-2","node-name":"libvirt-2-storage","cache":{"direct":false,"no-flush":false},"auto-read-only":true,"discard":"unmap"}' \
# -blockdev '{"node-name":"libvirt-2-format","read-only":false,"cache":{"direct":false,"no-flush":false},"driver":"qcow2","file":"libvirt-2-storage","backing":null}' \
# -device '{"driver":"ide-hd","bus":"ide.0","drive":"libvirt-2-format","id":"sata0-0-0","bootindex":1,"write-cache":"on"}' \
# -device '{"driver":"ide-cd","bus":"ide.2","id":"sata0-0-2"}' \
# -netdev user,id=hostnet0 \
# -device '{"driver":"rtl8139","netdev":"hostnet0","id":"net0","mac":"52:54:00:23:f7:a6","bus":"pci.5","addr":"0x1"}' \
# -chardev spicevmc,id=charsmartcard0,name=smartcard \
# -device '{"driver":"ccid-card-passthru","chardev":"charsmartcard0","id":"smartcard0","bus":"ccid0.0"}' \
# -chardev pty,id=charserial0 \
# -device '{"driver":"isa-serial","chardev":"charserial0","id":"serial0","index":0}' \
# -chardev spiceport,id=charchannel0,name=org.spice-space.webdav.0 \
# -device '{"driver":"virtserialport","bus":"virtio-serial0.0","nr":1,"chardev":"charchannel0","id":"channel0","name":"org.spice-space.webdav.0"}' \
# -chardev spicevmc,id=charchannel1,name=vdagent \
# -device '{"driver":"virtserialport","bus":"virtio-serial0.0","nr":2,"chardev":"charchannel1","id":"channel1","name":"com.redhat.spice.0"}' \
# -device '{"driver":"usb-tablet","id":"input0","bus":"usb.0","port":"2"}' \
# -audiodev '{"id":"audio1","driver":"spice"}' \
# -spice port=0,disable-ticketing=on,image-compression=off,seamless-migration=on \
# -device '{"driver":"qxl-vga","id":"video0","max_outputs":1,"ram_size":67108864,"vram_size":67108864,"vram64_size_mb":0,"vgamem_mb":16,"bus":"pcie.0","addr":"0x1"}' \
# -device '{"driver":"ich9-intel-hda","id":"sound0","bus":"pcie.0","addr":"0x1b"}' \
# -device '{"driver":"hda-duplex","id":"sound0-codec0","bus":"sound0.0","cad":0,"audiodev":"audio1"}' \
# -chardev spicevmc,id=charredir0,name=usbredir \
# -device '{"driver":"usb-redir","chardev":"charredir0","id":"redir0","bus":"usb.0","port":"3"}' \
# -chardev spicevmc,id=charredir1,name=usbredir \
# -device '{"driver":"usb-redir","chardev":"charredir1","id":"redir1","bus":"usb.0","port":"4"}' \
# -chardev spicevmc,id=charredir2,name=usbredir \
# -device '{"driver":"usb-redir","chardev":"charredir2","id":"redir2","bus":"usb.0","port":"5"}' \
# -chardev spicevmc,id=charredir3,name=usbredir \
# -device '{"driver":"usb-redir","chardev":"charredir3","id":"redir3","bus":"usb.0","port":"6"}' \
# -device '{"driver":"virtio-balloon-pci","id":"balloon0","bus":"pci.3","addr":"0x0"}' \
# -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny \
# -msg timestamp=on
