#!/bin/bash

set -e

# shellcheck source=~/.config/tmux/scripts/window-cmd
source "$XDG_CONFIG_HOME"/tmux/scripts/window-cmd

panes=$(tmux display -p '#{window_panes}')
test "$panes" -gt 1

tmux resize-pane -Z
